/**
 * The illustration registry (§2.5).
 *
 * Illustrations are React SVG components, not files in `public/`: they inherit
 * the palette tokens, they are theme-aware, and their alt text is a message key
 * so it is translated like everything else. The domain therefore knows an
 * illustration only by the **name** of its component; resolving the name to the
 * component happens in `components/illustrations/index.ts`, which keeps
 * `lib/domain` free of React.
 */
import * as z from "zod";

import { ID_PATTERN } from "../data/conventions";

/** The box the drawing is laid out in. Question aids are 4/3, option thumbnails square. */
export const ILLUSTRATION_ASPECTS = ["4/3", "1/1", "16/9"] as const;

/**
 * `placeholder` = generated by `scripts/gen-illustration-placeholders.ts`, a
 * labelled box that carries the right alt text; `final` = drawn by hand
 * (W2-T4c). The status is what `docs/illustrations.md` tracks and what a "still
 * to draw" report counts.
 */
export const ILLUSTRATION_STATUSES = ["placeholder", "final"] as const;

export type IllustrationAspect = (typeof ILLUSTRATION_ASPECTS)[number];
export type IllustrationStatus = (typeof ILLUSTRATION_STATUSES)[number];

export interface IllustrationDef {
  /** Exported component name, e.g. `IllDrive` — resolved at the React boundary. */
  component: string;
  /** `illustrations.<id>.alt` */
  altKey: string;
  aspect: IllustrationAspect;
  status: IllustrationStatus;
}

/** Component names are PascalCase and start with `Ill`. */
export const ILLUSTRATION_COMPONENT_PATTERN = /^Ill[A-Za-z0-9]*$/;

export const IllustrationDefSchema: z.ZodType<IllustrationDef> = z.strictObject({
  component: z.string().regex(ILLUSTRATION_COMPONENT_PATTERN),
  altKey: z.string().min(1),
  aspect: z.enum(ILLUSTRATION_ASPECTS),
  status: z.enum(ILLUSTRATION_STATUSES),
});

/**
 * Registry-wide refinements: ids are well-formed, alt keys are derived from the
 * id, and no two illustrations share a component. Returns one message per
 * problem.
 */
export function checkIllustrations(registry: Record<string, IllustrationDef>): string[] {
  const errors: string[] = [];
  const components = new Map<string, string>();

  for (const [id, definition] of Object.entries(registry)) {
    if (!ID_PATTERN.test(id)) errors.push(`${id}: not a well-formed illustration id`);
    if (definition.altKey !== `illustrations.${id}.alt`) {
      errors.push(`${id}: altKey must be "illustrations.${id}.alt"`);
    }
    const owner = components.get(definition.component);
    if (owner !== undefined) {
      errors.push(`${id}: component ${definition.component} is already used by ${owner}`);
    }
    components.set(definition.component, id);
  }

  return errors;
}

export const IllustrationRegistrySchema = z
  .record(z.string().regex(ID_PATTERN), IllustrationDefSchema)
  .check((ctx) => {
    for (const message of checkIllustrations(ctx.value)) {
      ctx.issues.push({ code: "custom", message, input: ctx.value });
    }
  });
