import { IllustrationPlaceholder, type IllustrationProps } from "./placeholder";

/**
 * `ill-cockpit-flat` — placeholder generated by `scripts/gen-illustration-placeholders.ts`.
 *
 * Replace the body with the real drawing and flip `status` to `"final"` in
 * `lib/domain/data/illustrations.ts`. Keep the exported name: the manifest
 * refers to it, and the barrel is generated from the files in this folder.
 */
export function IllCockpitFlat(props: IllustrationProps) {
  return <IllustrationPlaceholder id="ill-cockpit-flat" {...props} />;
}
