/**
 * Every illustration component, and the name → component map the renderer uses.
 *
 * GENERATED by `scripts/gen-illustration-placeholders.ts` — do not edit by hand; add an entry to
 * `lib/domain/data/illustrations.ts` (or drop an `Ill*.tsx` file in this
 * folder) and run the script again.
 *
 * The map is keyed by **component name** because that is what the manifest
 * stores: `ILLUSTRATIONS[id].component`. Keeping the indirection here is what
 * lets `lib/domain` describe drawings without importing React.
 */
import type { ComponentType } from "react";

import type { IllustrationProps } from "./placeholder";

import { IllAxleQrVsThru } from "./IllAxleQrVsThru";
import { IllBarrelAdjuster } from "./IllBarrelAdjuster";
import { IllBrakeMount } from "./IllBrakeMount";
import { IllBrakeType } from "./IllBrakeType";
import { IllBrakeTypeCantilever } from "./IllBrakeTypeCantilever";
import { IllBrakeTypeDiscHydraulic } from "./IllBrakeTypeDiscHydraulic";
import { IllBrakeTypeDiscMechanical } from "./IllBrakeTypeDiscMechanical";
import { IllBrakeTypeRimCaliper } from "./IllBrakeTypeRimCaliper";
import { IllBrakeTypeVBrake } from "./IllBrakeTypeVBrake";
import { IllChainWearChecker } from "./IllChainWearChecker";
import { IllCleatBallOfFoot } from "./IllCleatBallOfFoot";
import { IllCockpit } from "./IllCockpit";
import { IllCockpitDrop } from "./IllCockpitDrop";
import { IllCockpitFlat } from "./IllCockpitFlat";
import { IllCockpitRiser } from "./IllCockpitRiser";
import { IllCockpitSwept } from "./IllCockpitSwept";
import { IllDerailleurLimitScrewsHLB } from "./IllDerailleurLimitScrewsHLB";
import { IllDiscipline } from "./IllDiscipline";
import { IllDisciplineCityHybrid } from "./IllDisciplineCityHybrid";
import { IllDisciplineGravel } from "./IllDisciplineGravel";
import { IllDisciplineKids } from "./IllDisciplineKids";
import { IllDisciplineMtb } from "./IllDisciplineMtb";
import { IllDisciplineRoad } from "./IllDisciplineRoad";
import { IllDrive } from "./IllDrive";
import { IllDrivetrain } from "./IllDrivetrain";
import { IllDrivetrainDerailleur1x } from "./IllDrivetrainDerailleur1x";
import { IllDrivetrainDerailleur2x } from "./IllDrivetrainDerailleur2x";
import { IllDrivetrainDerailleur3x } from "./IllDrivetrainDerailleur3x";
import { IllDrivetrainIgh } from "./IllDrivetrainIgh";
import { IllDrivetrainSinglespeed } from "./IllDrivetrainSinglespeed";
import { IllEBattery } from "./IllEBattery";
import { IllEMotor } from "./IllEMotor";
import { IllEbikeBatteryConnector } from "./IllEbikeBatteryConnector";
import { IllHeadsetThreadedVsThreadless } from "./IllHeadsetThreadedVsThreadless";
import { IllPadWearDisc } from "./IllPadWearDisc";
import { IllPadWearRim } from "./IllPadWearRim";
import { IllPedals } from "./IllPedals";
import { IllPedalsCombo } from "./IllPedalsCombo";
import { IllPedalsFlat } from "./IllPedalsFlat";
import { IllPedalsRoadClipless } from "./IllPedalsRoadClipless";
import { IllPedalsSpd } from "./IllPedalsSpd";
import { IllPedalsToeClips } from "./IllPedalsToeClips";
import { IllPrestaValveCore } from "./IllPrestaValveCore";
import { IllRotorTrueCheck } from "./IllRotorTrueCheck";
import { IllSaddleHeightHeelMethod } from "./IllSaddleHeightHeelMethod";
import { IllSagMeasureOring } from "./IllSagMeasureOring";
import { IllSeatpost } from "./IllSeatpost";
import { IllShifter } from "./IllShifter";
import { IllShifterBarEnd } from "./IllShifterBarEnd";
import { IllShifterElectronic } from "./IllShifterElectronic";
import { IllShifterGrip } from "./IllShifterGrip";
import { IllShifterStiIntegrated } from "./IllShifterStiIntegrated";
import { IllShifterThumb } from "./IllShifterThumb";
import { IllShifterTrigger } from "./IllShifterTrigger";
import { IllSpeeds } from "./IllSpeeds";
import { IllSuspension } from "./IllSuspension";
import { IllTireLeverTechnique } from "./IllTireLeverTechnique";
import { IllTireSystem } from "./IllTireSystem";
import { IllTransmission } from "./IllTransmission";
import { IllWheelSize } from "./IllWheelSize";
import { IllWheelSize16 } from "./IllWheelSize16";
import { IllWheelSize20 } from "./IllWheelSize20";
import { IllWheelSize24 } from "./IllWheelSize24";
import { IllWheelSize26 } from "./IllWheelSize26";
import { IllWheelSize275 } from "./IllWheelSize275";
import { IllWheelSize29 } from "./IllWheelSize29";
import { IllWheelSize650b } from "./IllWheelSize650b";
import { IllWheelSize700c } from "./IllWheelSize700c";

export type { IllustrationProps };
export { IllustrationPlaceholder } from "./placeholder";

export { IllAxleQrVsThru };
export { IllBarrelAdjuster };
export { IllBrakeMount };
export { IllBrakeType };
export { IllBrakeTypeCantilever };
export { IllBrakeTypeDiscHydraulic };
export { IllBrakeTypeDiscMechanical };
export { IllBrakeTypeRimCaliper };
export { IllBrakeTypeVBrake };
export { IllChainWearChecker };
export { IllCleatBallOfFoot };
export { IllCockpit };
export { IllCockpitDrop };
export { IllCockpitFlat };
export { IllCockpitRiser };
export { IllCockpitSwept };
export { IllDerailleurLimitScrewsHLB };
export { IllDiscipline };
export { IllDisciplineCityHybrid };
export { IllDisciplineGravel };
export { IllDisciplineKids };
export { IllDisciplineMtb };
export { IllDisciplineRoad };
export { IllDrive };
export { IllDrivetrain };
export { IllDrivetrainDerailleur1x };
export { IllDrivetrainDerailleur2x };
export { IllDrivetrainDerailleur3x };
export { IllDrivetrainIgh };
export { IllDrivetrainSinglespeed };
export { IllEBattery };
export { IllEMotor };
export { IllEbikeBatteryConnector };
export { IllHeadsetThreadedVsThreadless };
export { IllPadWearDisc };
export { IllPadWearRim };
export { IllPedals };
export { IllPedalsCombo };
export { IllPedalsFlat };
export { IllPedalsRoadClipless };
export { IllPedalsSpd };
export { IllPedalsToeClips };
export { IllPrestaValveCore };
export { IllRotorTrueCheck };
export { IllSaddleHeightHeelMethod };
export { IllSagMeasureOring };
export { IllSeatpost };
export { IllShifter };
export { IllShifterBarEnd };
export { IllShifterElectronic };
export { IllShifterGrip };
export { IllShifterStiIntegrated };
export { IllShifterThumb };
export { IllShifterTrigger };
export { IllSpeeds };
export { IllSuspension };
export { IllTireLeverTechnique };
export { IllTireSystem };
export { IllTransmission };
export { IllWheelSize };
export { IllWheelSize16 };
export { IllWheelSize20 };
export { IllWheelSize24 };
export { IllWheelSize26 };
export { IllWheelSize275 };
export { IllWheelSize29 };
export { IllWheelSize650b };
export { IllWheelSize700c };

export const ILLUSTRATION_COMPONENTS: Record<string, ComponentType<IllustrationProps>> = {
  IllAxleQrVsThru,
  IllBarrelAdjuster,
  IllBrakeMount,
  IllBrakeType,
  IllBrakeTypeCantilever,
  IllBrakeTypeDiscHydraulic,
  IllBrakeTypeDiscMechanical,
  IllBrakeTypeRimCaliper,
  IllBrakeTypeVBrake,
  IllChainWearChecker,
  IllCleatBallOfFoot,
  IllCockpit,
  IllCockpitDrop,
  IllCockpitFlat,
  IllCockpitRiser,
  IllCockpitSwept,
  IllDerailleurLimitScrewsHLB,
  IllDiscipline,
  IllDisciplineCityHybrid,
  IllDisciplineGravel,
  IllDisciplineKids,
  IllDisciplineMtb,
  IllDisciplineRoad,
  IllDrive,
  IllDrivetrain,
  IllDrivetrainDerailleur1x,
  IllDrivetrainDerailleur2x,
  IllDrivetrainDerailleur3x,
  IllDrivetrainIgh,
  IllDrivetrainSinglespeed,
  IllEBattery,
  IllEMotor,
  IllEbikeBatteryConnector,
  IllHeadsetThreadedVsThreadless,
  IllPadWearDisc,
  IllPadWearRim,
  IllPedals,
  IllPedalsCombo,
  IllPedalsFlat,
  IllPedalsRoadClipless,
  IllPedalsSpd,
  IllPedalsToeClips,
  IllPrestaValveCore,
  IllRotorTrueCheck,
  IllSaddleHeightHeelMethod,
  IllSagMeasureOring,
  IllSeatpost,
  IllShifter,
  IllShifterBarEnd,
  IllShifterElectronic,
  IllShifterGrip,
  IllShifterStiIntegrated,
  IllShifterThumb,
  IllShifterTrigger,
  IllSpeeds,
  IllSuspension,
  IllTireLeverTechnique,
  IllTireSystem,
  IllTransmission,
  IllWheelSize,
  IllWheelSize16,
  IllWheelSize20,
  IllWheelSize24,
  IllWheelSize26,
  IllWheelSize275,
  IllWheelSize29,
  IllWheelSize650b,
  IllWheelSize700c,
};

/** The component that draws `name`, or `undefined` if nobody has drawn it yet. */
export function illustrationComponent(name: string): ComponentType<IllustrationProps> | undefined {
  // eslint-disable-next-line security/detect-object-injection -- guarded by Object.hasOwn, so prototype keys are unreachable
  return Object.hasOwn(ILLUSTRATION_COMPONENTS, name) ? ILLUSTRATION_COMPONENTS[name] : undefined;
}
