"use client";

import { Eye, EyeOff } from "lucide-react";
import { useId, useState } from "react";
import { useFormStatus } from "react-dom";
import { useTranslations } from "next-intl";

import type { FormResult } from "@/lib/actions/result";
import { translateScopedKey, type ScopedTranslator } from "@/lib/i18n/scoped-key";

/**
 * The pieces every auth and account form is built from.
 *
 * shadcn's `Input` / `Label` / `Button` are generated by W1-T5 and did not exist
 * when these forms were written; more to the point, the behaviour that matters
 * here is not styling. It is:
 *
 * - **message keys, never sentences.** `fieldMessage()` takes the
 *   `ActionResult.fieldErrors` value — a fully qualified key such as
 *   `errors.invalidCredentials` or `auth.password.tooShort` — and renders it
 *   in the visitor's locale, so the same action drives the French and the
 *   English page. (bd-platform hard-codes French in its actions; that is the one
 *   convention from it this project does not copy.) Every key an auth or account
 *   action returns is `errors.*` or `auth.*`, so they are resolved inside those
 *   two namespaces (`useActionMessage` below) rather than by a root translator,
 *   which would make every route with a form ship the whole catalogue
 *   (`.debug/008`).
 * - **44 px targets and 16 px text** on every control, so iOS does not zoom on
 *   focus and §6.8 AC5 holds at 320 px.
 * - **`aria-invalid` + `aria-describedby`** wired from the same result, and an
 *   `aria-live` region for the form-level slot, so a screen reader hears the
 *   failure without hunting for it.
 * - a submit button that **stays enabled** while a field is invalid: disabling
 *   it hides the reason and strands anyone whose JavaScript did not load. It is
 *   disabled only while the submission is in flight.
 */

const inputClass =
  "w-full rounded-md border border-rule bg-paper px-3 py-2 text-base text-ink " +
  "placeholder:text-ink-muted focus-visible:border-accent min-h-[var(--tap-min)] " +
  "aria-[invalid=true]:border-danger";

/**
 * A message KEY an auth or account action returned, translated: `errors.*` (the
 * headline codes and the field refusals) or `auth.*` (the password policy's
 * `auth.password.<issue>`). Anything else is reported missing by next-intl
 * instead of being resolved in some other namespace (`translateScopedKey`).
 */
function useActionMessage(): (key: string) => string {
  const errors = useTranslations("errors") as unknown as ScopedTranslator;
  const auth = useTranslations("auth") as unknown as ScopedTranslator;
  return (key) => translateScopedKey(key, { errors, auth });
}

/** The message for one field of a failed result, already translated. */
export function useFieldMessage(result: FormResult) {
  const message = useActionMessage();
  return (field: string): string | undefined => {
    if (result.ok) return undefined;
    // eslint-disable-next-line security/detect-object-injection -- reading a plain record the action built; `field` is a form input name
    const key = result.fieldErrors?.[field];
    return key === undefined ? undefined : message(key);
  };
}

/**
 * The form-level error region.
 *
 * Always rendered — `sr-only` and empty while there is nothing to say — so that
 * `aria-live` has a region to announce into rather than one appearing under the
 * screen reader mid-announcement.
 *
 * `testId` exists because several of these can share a page: the login page
 * carries one for the credentials form and one for the Google form, and
 * `/compte` carries one per section. A single shared `data-testid` made
 * `getByTestId('form-error')` a strict-mode violation in Playwright — one
 * region per form, each named, is both easier to assert on and a truer
 * description of the page.
 */
export function FormError({
  result,
  id,
  testId = "form-error",
}: {
  result: FormResult;
  id?: string;
  /** Unique within the page when more than one form is rendered. */
  testId?: string;
}): React.JSX.Element {
  const actionMessage = useActionMessage();
  const tErrors = useTranslations("errors");
  const message =
    result.ok || result.fieldErrors?.form === undefined
      ? result.ok
        ? undefined
        : tErrors(result.code)
      : actionMessage(result.fieldErrors.form);

  const retry =
    !result.ok && result.retryAfterSec !== undefined && result.retryAfterSec > 0
      ? result.retryAfterSec >= 60
        ? tErrors("retryAfterMinutes", { minutes: Math.ceil(result.retryAfterSec / 60) })
        : tErrors("retryAfter", { seconds: result.retryAfterSec })
      : undefined;

  return (
    <p
      id={id}
      role="alert"
      aria-live="polite"
      data-testid={testId}
      className={message ? "rounded-md bg-paper-2 p-3 text-sm text-danger-fg" : "sr-only"}
    >
      {message ? [message, retry].filter(Boolean).join(" ") : ""}
    </p>
  );
}

interface FieldProps {
  /** Omit for a display-only field: an input without a name is not submitted. */
  name?: string;
  label: string;
  error?: string;
  hint?: string;
  autoComplete?: string;
  required?: boolean;
  defaultValue?: string;
  readOnly?: boolean;
  type?: "text" | "email";
  inputMode?: "text" | "email";
}

export function TextField({
  name,
  label,
  error,
  hint,
  autoComplete,
  required,
  defaultValue,
  readOnly,
  type = "text",
  inputMode,
}: FieldProps): React.JSX.Element {
  const id = useId();
  const errorId = `${id}-error`;
  const hintId = `${id}-hint`;
  const describedBy = [hint ? hintId : null, error ? errorId : null].filter(Boolean).join(" ");

  return (
    <div className="space-y-1">
      <label htmlFor={id} className="block text-sm font-medium text-ink">
        {label}
      </label>
      <input
        id={id}
        name={name}
        type={type}
        inputMode={inputMode}
        autoComplete={autoComplete}
        required={required}
        defaultValue={defaultValue}
        readOnly={readOnly}
        aria-invalid={error ? true : undefined}
        aria-describedby={describedBy || undefined}
        className={inputClass}
      />
      {hint ? (
        <p id={hintId} className="text-xs text-ink-muted">
          {hint}
        </p>
      ) : null}
      {error ? (
        <p id={errorId} className="text-sm text-danger-fg">
          {error}
        </p>
      ) : null}
    </div>
  );
}

export function PasswordField({
  name,
  label,
  error,
  hint,
  autoComplete,
  value,
  onValueChange,
  describedById,
  children,
}: {
  name: string;
  label: string;
  error?: string;
  hint?: string;
  autoComplete: "current-password" | "new-password";
  /** Controlled only when the meter needs to watch it. */
  value?: string;
  onValueChange?: (value: string) => void;
  describedById?: string;
  /** The strength meter, rendered under the input. */
  children?: React.ReactNode;
}): React.JSX.Element {
  const t = useTranslations("auth");
  const id = useId();
  const errorId = `${id}-error`;
  const hintId = `${id}-hint`;
  const [visible, setVisible] = useState(false);
  const describedBy = [hint ? hintId : null, describedById ?? null, error ? errorId : null]
    .filter(Boolean)
    .join(" ");

  return (
    <div className="space-y-1">
      <label htmlFor={id} className="block text-sm font-medium text-ink">
        {label}
      </label>
      <div className="relative">
        <input
          id={id}
          name={name}
          type={visible ? "text" : "password"}
          autoComplete={autoComplete}
          required
          value={value}
          onChange={onValueChange ? (event) => onValueChange(event.target.value) : undefined}
          aria-invalid={error ? true : undefined}
          aria-describedby={describedBy || undefined}
          className={`${inputClass} pr-14`}
        />
        {/* A fixed 44 px icon, not a text label: "Afficher le mot de passe" was wide
            enough at 320 px to cover the middle of the field (which reserves only
            pr-14), so a tap meant for the field revealed the password instead
            (.debug/003). The name stays for assistive tech via the sr-only text. */}
        <button
          type="button"
          onClick={() => setVisible((shown) => !shown)}
          aria-pressed={visible}
          className="tap-target absolute inset-y-0 right-0 rounded-md text-ink-muted hover:text-ink"
        >
          {visible ? (
            <EyeOff aria-hidden="true" className="size-5" />
          ) : (
            <Eye aria-hidden="true" className="size-5" />
          )}
          <span className="sr-only">{visible ? t("hidePassword") : t("showPassword")}</span>
        </button>
      </div>
      {hint ? (
        <p id={hintId} className="text-xs text-ink-muted">
          {hint}
        </p>
      ) : null}
      {children}
      {error ? (
        <p id={errorId} className="text-sm text-danger-fg">
          {error}
        </p>
      ) : null}
    </div>
  );
}

/**
 * Submit button. Enabled unless the submission is in flight — see the header
 * comment for why it is never disabled on validity.
 */
export function SubmitButton({
  label,
  pendingLabel,
  tone = "accent",
  className = "",
  children,
}: {
  label: string;
  pendingLabel: string;
  /** Rendered before the label — a provider mark, an icon. */
  tone?: "accent" | "danger" | "ghost";
  className?: string;
  children?: React.ReactNode;
}): React.JSX.Element {
  const { pending } = useFormStatus();
  // eslint-disable-next-line security/detect-object-injection -- `tone` is one of three literals
  const toneClass = {
    accent: "bg-accent text-accent-fg hover:opacity-90",
    danger: "bg-danger text-white hover:opacity-90",
    ghost: "border border-rule bg-paper text-ink hover:bg-paper-2",
  }[tone];
  return (
    <button
      type="submit"
      disabled={pending}
      aria-busy={pending}
      className={`tap-target w-full gap-2 rounded-md px-4 text-base font-semibold disabled:opacity-60 ${toneClass} ${className}`}
    >
      {children}
      {pending ? pendingLabel : label}
    </button>
  );
}

/**
 * A short confirmation shown after a successful account action.
 *
 * `testId` for the same reason as `FormError`: `/compte` renders three of
 * these, and a shared id makes every assertion on one of them ambiguous.
 */
export function SuccessNote({
  result,
  message,
  testId = "form-success",
}: {
  result: FormResult;
  message: string;
  /** Unique within the page when more than one form is rendered. */
  testId?: string;
}): React.JSX.Element | null {
  if (!result.ok || !result.data) return null;
  return (
    <p role="status" className="text-sm text-success-fg" data-testid={testId}>
      {message}
    </p>
  );
}
