/**
 * Regenerate `lib/auth/common-passwords.ts` from the SecLists top-10k list.
 *
 *   npx tsx scripts/gen-common-passwords.ts                 # fetch from GitHub
 *   npx tsx scripts/gen-common-passwords.ts --from list.txt # from a local copy
 *   npx tsx scripts/gen-common-passwords.ts --check         # fail if stale
 *
 * The list is vendored rather than fetched at runtime: a sign-up must not
 * depend on a third-party host being up, and 10 000 strings compress to about
 * 70 kB of source that never reaches the browser (the policy module that reads
 * it is `server-only`).
 *
 * Source: SecLists, `Passwords/Common-Credentials/10k-most-common.txt`, MIT.
 * Attribution lives in `THIRD_PARTY_NOTICES.md`.
 *
 * Plain Node — no `server-only`, no Next imports (`tests/unit/no-server-only-in-scripts.test.ts`
 * walks this file's import graph).
 */

import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { argv, exit } from "node:process";

const SOURCE_URL =
  "https://raw.githubusercontent.com/danielmiessler/SecLists/master/Passwords/Common-Credentials/10k-most-common.txt";

const OUTPUT = path.join(process.cwd(), "lib", "auth", "common-passwords.ts");

/** Passwords per emitted chunk — keeps single source lines under ~2 kB. */
const CHUNK_SIZE = 200;

interface Options {
  from?: string;
  check: boolean;
}

function parseArgs(args: readonly string[]): Options {
  const options: Options = { check: false };
  for (let i = 0; i < args.length; i += 1) {
    // eslint-disable-next-line security/detect-object-injection -- `i` is a loop counter over the argv array
    const arg = args[i];
    if (arg === "--check") options.check = true;
    else if (arg === "--from") options.from = args[i + 1];
    else if (arg.startsWith("--from=")) options.from = arg.slice("--from=".length);
  }
  return options;
}

async function readSource(options: Options): Promise<string> {
  if (options.from) {
    // eslint-disable-next-line security/detect-non-literal-fs-filename -- an operator-supplied path is the point of --from
    return readFileSync(options.from, "utf8");
  }
  const response = await fetch(SOURCE_URL);
  if (!response.ok) {
    throw new Error(`${SOURCE_URL} answered ${response.status} ${response.statusText}`);
  }
  return response.text();
}

/**
 * Normalise the raw list: lower-case, de-duplicated, sorted, blank lines gone.
 *
 * The whole list is kept, short entries included, even though the length rule
 * runs first and refuses anything under `PASSWORD_MIN_LENGTH` before the
 * membership test is reached. Measured on the SecLists top-10k: only 10 of its
 * 9 999 entries are 12 characters or longer. Filtering the rest out would
 * shrink the module to a rounding error and make it a liability the day the
 * minimum length changes — the list is the list, and the policy decides which
 * rule speaks first (a short password is told "too short", never "too common").
 */
export function normalizeList(raw: string): string[] {
  const seen = new Set<string>();
  for (const line of raw.split(/\r?\n/)) {
    const password = line.trim().toLowerCase();
    if (password.length === 0) continue;
    seen.add(password);
  }
  return [...seen].sort();
}

function chunk<T>(items: readonly T[], size: number): T[][] {
  const chunks: T[][] = [];
  for (let i = 0; i < items.length; i += size) chunks.push(items.slice(i, i + size));
  return chunks;
}

export function renderModule(passwords: readonly string[]): string {
  const chunks = chunk(passwords, CHUNK_SIZE)
    .map((group) => `  ${JSON.stringify(group.join("\n"))},`)
    .join("\n");

  return `/**
 * The ${passwords.length} most common passwords.
 *
 * GENERATED by \`npx tsx scripts/gen-common-passwords.ts\` from SecLists
 * (\`Passwords/Common-Credentials/10k-most-common.txt\`, MIT — see
 * THIRD_PARTY_NOTICES.md). Do not edit by hand.
 *
 * The list is vendored whole. The length rule runs first, so a short entry can
 * never be the reason a password is refused — a short password is told "too
 * short", never "too common".
 *
 * Stored newline-joined and split once at import: one \`Set\` lookup per sign-up,
 * a fraction of the parse cost of a 10 000-element array literal, and a diff
 * that stays readable. Read only by \`lib/auth/password-policy.ts\`, which is
 * \`server-only\` — this list never reaches the browser.
 */

const CHUNKS: readonly string[] = [
${chunks}
];

export const COMMON_PASSWORDS: ReadonlySet<string> = new Set(CHUNKS.join("\\n").split("\\n"));

/** Case-insensitive membership test. */
export function isCommonPassword(password: string): boolean {
  return COMMON_PASSWORDS.has(password.toLowerCase());
}
`;
}

async function main(): Promise<void> {
  const options = parseArgs(argv.slice(2));
  const raw = await readSource(options);
  const passwords = normalizeList(raw);
  if (passwords.length < 1000) {
    throw new Error(`Refusing to write a list of only ${passwords.length} entries.`);
  }
  const next = renderModule(passwords);

  if (options.check) {
    const current = readFileSync(OUTPUT, "utf8");
    if (current !== next) {
      console.error("lib/auth/common-passwords.ts is stale — re-run without --check.");
      exit(1);
    }
    console.log(`lib/auth/common-passwords.ts is up to date (${passwords.length} entries).`);
    return;
  }

  writeFileSync(OUTPUT, next, "utf8");
  console.log(`Wrote ${passwords.length} passwords to lib/auth/common-passwords.ts`);
}

// Only when run as a script: a unit test imports `normalizeList` / `renderModule`
// without regenerating anything.
if (/gen-common-passwords\.ts$/.test(argv[1] ?? "")) {
  main().catch((error: unknown) => {
    console.error(error instanceof Error ? `✖ ${error.message}` : error);
    process.exitCode = 1;
  });
}
