#!/usr/bin/env tsx
/**
 * Generate the missing illustration components and rewrite their barrel.
 *
 *   npx tsx scripts/gen-illustration-placeholders.ts            # create + rewrite
 *   npx tsx scripts/gen-illustration-placeholders.ts --check    # fail if anything is missing
 *
 * Every id in `lib/domain/data/illustrations.ts` needs a component, or the
 * decision tree renders a hole. This script creates a labelled placeholder for
 * the ones that have none, so the manifest can grow an entry at a time and the
 * tree keeps validating; a real drawing that already exists is **never**
 * touched, and nothing is ever deleted (removing a component is a human's call,
 * on purpose).
 *
 * The barrel it rewrites (`components/illustrations/index.ts`) exports every
 * `Ill*.tsx` file it finds — not only the ones in the manifest — so a later
 * task can add guide illustrations without this script undoing the work.
 * Components are keyed there by **component name**, which is what the manifest
 * stores: that is the seam that keeps `lib/domain` free of React.
 *
 * Plain Node (`tsx`): no `server-only` anywhere in its import graph
 * (`tests/unit/no-server-only-in-scripts.test.ts`).
 */
/* eslint-disable security/detect-non-literal-fs-filename -- every path below is built from the repo root plus a component name matched against /^Ill[A-Za-z0-9]*$/ */
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { ILLUSTRATIONS } from "../lib/domain/data/illustrations";

const COMPONENT_DIR = join(process.cwd(), "components", "illustrations");
const BARREL = join(COMPONENT_DIR, "index.ts");
const COMPONENT_NAME = /^Ill[A-Za-z0-9]*$/;

const GENERATED_BY = "scripts/gen-illustration-placeholders.ts";

function placeholderSource(id: string, component: string): string {
  return `import { IllustrationPlaceholder, type IllustrationProps } from "./placeholder";

/**
 * \`${id}\` — placeholder generated by \`${GENERATED_BY}\`.
 *
 * Replace the body with the real drawing and flip \`status\` to \`"final"\` in
 * \`lib/domain/data/illustrations.ts\`. Keep the exported name: the manifest
 * refers to it, and the barrel is generated from the files in this folder.
 */
export function ${component}(props: IllustrationProps) {
  return <IllustrationPlaceholder id="${id}" {...props} />;
}
`;
}

function barrelSource(components: readonly string[]): string {
  const imports = components
    .map((component) => `import { ${component} } from "./${component}";`)
    .join("\n");
  const entries = components.map((component) => `  ${component},`).join("\n");
  const exports = components.map((component) => `export { ${component} };`).join("\n");

  return `/**
 * Every illustration component, and the name → component map the renderer uses.
 *
 * GENERATED by \`${GENERATED_BY}\` — do not edit by hand; add an entry to
 * \`lib/domain/data/illustrations.ts\` (or drop an \`Ill*.tsx\` file in this
 * folder) and run the script again.
 *
 * The map is keyed by **component name** because that is what the manifest
 * stores: \`ILLUSTRATIONS[id].component\`. Keeping the indirection here is what
 * lets \`lib/domain\` describe drawings without importing React.
 */
import type { ComponentType } from "react";

import type { IllustrationProps } from "./placeholder";

${imports}

export type { IllustrationProps };
export { IllustrationPlaceholder } from "./placeholder";

${exports}

export const ILLUSTRATION_COMPONENTS: Record<string, ComponentType<IllustrationProps>> = {
${entries}
};

/** The component that draws \`name\`, or \`undefined\` if nobody has drawn it yet. */
export function illustrationComponent(name: string): ComponentType<IllustrationProps> | undefined {
  // eslint-disable-next-line security/detect-object-injection -- guarded by Object.hasOwn, so prototype keys are unreachable
  return Object.hasOwn(ILLUSTRATION_COMPONENTS, name) ? ILLUSTRATION_COMPONENTS[name] : undefined;
}
`;
}

/** Component names present on disk, whatever their origin. */
function componentsOnDisk(): string[] {
  if (!existsSync(COMPONENT_DIR)) return [];
  return readdirSync(COMPONENT_DIR)
    .filter((file) => file.endsWith(".tsx"))
    .map((file) => file.slice(0, -".tsx".length))
    .filter((name) => COMPONENT_NAME.test(name))
    .sort();
}

function main(): void {
  const check = process.argv.includes("--check");
  mkdirSync(COMPONENT_DIR, { recursive: true });

  const missing: string[] = [];
  for (const [id, definition] of Object.entries(ILLUSTRATIONS)) {
    const file = join(COMPONENT_DIR, `${definition.component}.tsx`);
    if (existsSync(file)) continue;
    missing.push(`${id} → ${definition.component}.tsx`);
    if (!check) writeFileSync(file, placeholderSource(id, definition.component), "utf8");
  }

  if (check && missing.length > 0) {
    console.error(`Missing ${missing.length} illustration component(s):`);
    for (const entry of missing) console.error(`  ${entry}`);
    console.error(`Run: npx tsx ${GENERATED_BY}`);
    process.exitCode = 1;
    return;
  }

  const components = componentsOnDisk();
  const barrel = barrelSource(components);
  const current = existsSync(BARREL) ? readFileSync(BARREL, "utf8") : "";

  if (check) {
    if (current !== barrel) {
      console.error(`${BARREL} is out of date. Run: npx tsx ${GENERATED_BY}`);
      process.exitCode = 1;
      return;
    }
    console.log(`illustrations: ${components.length} components, barrel up to date.`);
    return;
  }

  if (current !== barrel) writeFileSync(BARREL, barrel, "utf8");
  console.log(
    `illustrations: ${missing.length} placeholder(s) created, ${components.length} component(s) exported.`,
  );
}

main();
