#!/usr/bin/env tsx
/**
 * First-load JavaScript budget.
 *
 * Reads `perf.budgets.json` (the single source of truth for every size number),
 * measures what a browser actually downloads before each budgeted route is
 * interactive, prints a table, appends it to `$GITHUB_STEP_SUMMARY`, and exits
 * 1 on a breach.
 *
 * What "first load" means here
 * ---------------------------
 * shared framework chunks + the route's own EAGER client chunks, gzipped.
 * Excluded on purpose:
 *   - `polyfillFiles`: served `nomodule`, no modern browser downloads them;
 *   - CSS: a stylesheet regression is a different problem with a different fix;
 *   - `async: true` client modules: those are the lazily-imported chunks (the
 *     3D viewer above all), and keeping them OUT of this number is exactly what
 *     makes `forbidWebgl` below meaningful.
 *
 * Where the numbers come from
 * ---------------------------
 * §7.3 of the plan says `.next/app-build-manifest.json`. That file is a webpack
 * artefact; a Next 16.3.4 **Turbopack** build does not emit it (verified
 * 2026-09-11 — `.next/` contains `build-manifest.json` and per-route
 * `.next/server/app/<route>/page/build-manifest.json` instead). So the manifest
 * is resolved through a chain:
 *
 *   1. `.next/app-build-manifest.json`                      (webpack build)
 *   2. `.next/server/app/<route>/page/build-manifest.json`  (Turbopack: shared
 *      chunks) + `.next/server/app/<route>/page_client-reference-manifest.js`
 *      (Turbopack: the route's own client chunks, with the async flag)
 *
 * A budgeted route that has not been built yet is reported as `not built` and
 * does not fail the run — the budget exists before the page does.
 *
 * Units: every size printed is KiB (1024 bytes) and says so; the budgets in
 * `perf.budgets.json` are bytes. (The table used to print KiB labelled "kB",
 * which is how the W0 pin ended up with 8 % headroom instead of 10 %.)
 *
 * Flags:
 *   --json                      raw gzip bytes and the ratchet's `nextPin` per
 *                               route; always exits 0 (it is for re-pinning)
 *   --budget <route>=<bytes>    replace one route's ceiling for this run only,
 *                               e.g. `--budget '/[locale]=1000'` — §7.6 AC8's
 *                               "set a budget to 1000 and it must exit 1", the
 *                               way to prove the gate is live without editing
 *                               the committed file. Repeatable.
 */
import { gzipSync } from "node:zlib";
import { existsSync, readFileSync, appendFileSync } from "node:fs";
import path from "node:path";

const ROOT = process.cwd();
const NEXT_DIR = path.join(ROOT, ".next");
const BUDGETS_FILE = path.join(ROOT, "perf.budgets.json");

interface RouteBudget {
  label: string;
  firstLoadJsGzipBytes: number;
  targetGzipBytes?: number;
  forbidWebgl?: boolean;
}

interface Budgets {
  routes: Record<string, RouteBudget>;
  webglMarker: string;
  lazy3dChunkGzipBytes: number;
}

interface TurbopackBuildManifest {
  rootMainFiles?: string[];
  polyfillFiles?: string[];
  pages?: Record<string, string[]>;
}

interface ClientModuleEntry {
  chunks?: string[];
  async?: boolean;
}

interface RouteChunks {
  eager: string[];
  lazy: string[];
}

type Verdict = "ok" | "over" | "missing";

interface Measurement {
  route: string;
  label: string;
  verdict: Verdict;
  gzipBytes: number;
  budget: number;
  target?: number;
  webglChunks: string[];
}

/* eslint-disable security/detect-non-literal-fs-filename --
   Every path handed to fs below is built from `perf.budgets.json` (committed)
   or from a Next build manifest inside `.next/` (generated by our own build).
   None of it is user input; this script only ever runs in CI or from a
   developer's shell. */

function readJson<T>(file: string): T {
  return JSON.parse(readFileSync(file, "utf8")) as T;
}

/** `/[locale]/guides/[slug]` -> `[locale]/guides/[slug]` (`/` -> ``). */
function routeToSegment(route: string): string {
  return route.replace(/^\/+/, "");
}

/** `static/chunks/x.js` and `/_next/static/chunks/x.js` -> `<root>/.next/static/chunks/x.js` */
function chunkToFile(chunk: string): string {
  const relative = chunk.replace(/^\/?_next\//, "").replace(/^\/+/, "");
  return path.join(NEXT_DIR, relative);
}

function isJs(file: string): boolean {
  return file.endsWith(".js");
}

/** Turbopack writes the route's client modules as a `globalThis.__RSC_MANIFEST[...] = {...};` assignment. */
function parseClientReferenceManifest(file: string): Record<string, ClientModuleEntry> {
  const source = readFileSync(file, "utf8");
  const marker = "] = ";
  const start = source.lastIndexOf(marker);
  if (start === -1) return {};
  const json = source.slice(start + marker.length).replace(/;?\s*$/, "");
  try {
    const parsed = JSON.parse(json) as { clientModules?: Record<string, ClientModuleEntry> };
    return parsed.clientModules ?? {};
  } catch {
    return {};
  }
}

function collectChunks(route: string): RouteChunks | null {
  const segment = routeToSegment(route);

  // 1. webpack build
  const appBuildManifest = path.join(NEXT_DIR, "app-build-manifest.json");
  if (existsSync(appBuildManifest)) {
    const manifest = readJson<{ pages: Record<string, string[]> }>(appBuildManifest);
    const key = `${route}/page`;
    const files = Object.prototype.hasOwnProperty.call(manifest.pages, key)
      ? // eslint-disable-next-line security/detect-object-injection -- `key` comes from perf.budgets.json and the own-property check above.
        manifest.pages[key]
      : undefined;
    if (files) return { eager: files, lazy: [] };
    return null;
  }

  // 2. Turbopack build
  const routeDir = path.join(NEXT_DIR, "server", "app", segment);
  const buildManifest = path.join(routeDir, "page", "build-manifest.json");
  if (!existsSync(buildManifest)) return null;

  const manifest = readJson<TurbopackBuildManifest>(buildManifest);
  const eager = new Set<string>(manifest.rootMainFiles ?? []);
  const lazy = new Set<string>();

  const clientManifest = path.join(routeDir, "page_client-reference-manifest.js");
  if (existsSync(clientManifest)) {
    const modules = parseClientReferenceManifest(clientManifest);
    for (const entry of Object.values(modules)) {
      for (const chunk of entry.chunks ?? []) {
        (entry.async === true ? lazy : eager).add(chunk);
      }
    }
  }

  return { eager: [...eager], lazy: [...lazy] };
}

function gzipBytesOf(files: string[]): number {
  let total = 0;
  for (const file of files) {
    if (!existsSync(file)) continue;
    total += gzipSync(readFileSync(file)).length;
  }
  return total;
}

function measure(route: string, budget: RouteBudget, webglMarker: string): Measurement {
  const chunks = collectChunks(route);
  if (!chunks) {
    return {
      route,
      label: budget.label,
      verdict: "missing",
      gzipBytes: 0,
      budget: budget.firstLoadJsGzipBytes,
      target: budget.targetGzipBytes,
      webglChunks: [],
    };
  }

  const eagerFiles = [...new Set(chunks.eager.map(chunkToFile))].filter(isJs);
  const gzipBytes = gzipBytesOf(eagerFiles);

  const webglChunks: string[] = [];
  if (budget.forbidWebgl) {
    for (const file of eagerFiles) {
      if (!existsSync(file)) continue;
      if (readFileSync(file, "utf8").includes(webglMarker)) {
        webglChunks.push(path.relative(ROOT, file));
      }
    }
  }

  return {
    route,
    label: budget.label,
    verdict: gzipBytes > budget.firstLoadJsGzipBytes ? "over" : "ok",
    gzipBytes,
    budget: budget.firstLoadJsGzipBytes,
    target: budget.targetGzipBytes,
    webglChunks,
  };
}

/* eslint-enable security/detect-non-literal-fs-filename */

function kib(bytes: number): string {
  return `${(bytes / 1024).toFixed(1)} KiB`;
}

/** `--budget <route>=<bytes>` pairs from argv, validated against the budgeted routes. */
function overridesFrom(argv: readonly string[], routes: ReadonlySet<string>): Map<string, number> {
  const overrides = new Map<string, number>();
  argv.forEach((arg, index) => {
    const value =
      arg === "--budget" ? argv[index + 1] : arg.startsWith("--budget=") ? arg.slice(9) : null;
    if (value === null || value === undefined) return;
    const at = value.lastIndexOf("=");
    const route = value.slice(0, at);
    const bytes = Number(value.slice(at + 1));
    if (at <= 0 || !Number.isInteger(bytes) || bytes <= 0) {
      console.error(`--budget ${value}: expected <route>=<positive whole bytes>`);
      process.exit(2);
    }
    if (!routes.has(route)) {
      console.error(
        `--budget ${value}: ${route} is not a budgeted route (${[...routes].join(", ")})`,
      );
      process.exit(2);
    }
    overrides.set(route, bytes);
  });
  return overrides;
}

function main(): void {
  if (!existsSync(BUDGETS_FILE)) {
    console.error("perf.budgets.json not found");
    process.exit(1);
  }
  if (!existsSync(NEXT_DIR)) {
    console.error("no .next/ — run `npm run build` first");
    process.exit(1);
  }

  const budgets = readJson<Budgets>(BUDGETS_FILE);
  const overrides = overridesFrom(process.argv, new Set(Object.keys(budgets.routes)));
  for (const [route, bytes] of overrides) {
    console.warn(`OVERRIDE: ${route} budget set to ${bytes} B for this run (--budget)`);
  }
  const measurements = Object.entries(budgets.routes).map(([route, budget]) =>
    measure(
      route,
      overrides.has(route) ? { ...budget, firstLoadJsGzipBytes: overrides.get(route)! } : budget,
      budgets.webglMarker,
    ),
  );

  // `--json` prints raw bytes and the ratchet's next ceiling (measured + 10 %,
  // rounded up to a whole KiB). The table rounds to 0.1 KiB, which is not enough
  // to re-pin `firstLoadJsGzipBytes` at a wave integration without guessing.
  if (process.argv.includes("--json")) {
    console.log(
      JSON.stringify(
        measurements.map((m) => ({
          route: m.route,
          gzipBytes: m.gzipBytes,
          budget: m.budget,
          verdict: m.verdict,
          nextPin: Math.ceil((m.gzipBytes * 1.1) / 1024) * 1024,
        })),
        null,
        2,
      ),
    );
    return;
  }

  const rows = measurements.map((m) => {
    const size = m.verdict === "missing" ? "not built" : kib(m.gzipBytes);
    const headroom =
      m.verdict === "missing"
        ? "—"
        : `${(((m.budget - m.gzipBytes) / m.budget) * 100).toFixed(0)}%`;
    const status = m.verdict === "over" ? "OVER" : m.verdict === "missing" ? "skip" : "ok";
    return {
      Route: m.route,
      "First-load JS (gzip)": size,
      Budget: kib(m.budget),
      Headroom: headroom,
      Target: m.target ? kib(m.target) : "—",
      Status: status,
    };
  });

  console.log("\nBundle budget — first-load JS, gzipped\n");
  console.table(rows);

  const failures: string[] = [];
  for (const m of measurements) {
    if (m.verdict === "over") {
      failures.push(
        `${m.route}: ${kib(m.gzipBytes)} exceeds the ${kib(m.budget)} budget by ${kib(m.gzipBytes - m.budget)}`,
      );
    }
    if (m.webglChunks.length > 0) {
      failures.push(
        `${m.route}: eager chunk(s) contain "${budgets.webglMarker}" — the 3D viewer must stay lazily imported (${m.webglChunks.join(", ")})`,
      );
    }
    if (m.verdict === "missing") {
      console.warn(`WARNING: ${m.route} is not in this build yet — budget not enforced.`);
    }
  }

  const summaryFile = process.env.GITHUB_STEP_SUMMARY;
  if (summaryFile) {
    const header = "| Route | First-load JS (gzip) | Budget | Headroom | Target | Status |";
    const divider = "|---|---|---|---|---|---|";
    const body = rows
      .map(
        (r) =>
          `| \`${r.Route}\` | ${r["First-load JS (gzip)"]} | ${r.Budget} | ${r.Headroom} | ${r.Target} | ${r.Status} |`,
      )
      .join("\n");
    const failureBlock =
      failures.length > 0 ? `\n\n**Breaches**\n\n${failures.map((f) => `- ${f}`).join("\n")}` : "";
    // eslint-disable-next-line security/detect-non-literal-fs-filename -- GITHUB_STEP_SUMMARY is set by the runner, not by a user.
    appendFileSync(
      summaryFile,
      `\n### Bundle budget\n\n${header}\n${divider}\n${body}${failureBlock}\n`,
    );
  }

  if (failures.length > 0) {
    console.error("\nBundle budget breached:");
    for (const failure of failures) console.error(`  - ${failure}`);
    process.exit(1);
  }

  console.log("Bundle budget respected.\n");
}

main();
